sudo: false
language: php
php:
 - '5.5'
 - '5.6'
 - '7.1'

env:
 - CUSTOM_ERROR_TRAP=1
 - CUSTOM_ERROR_TRAP=0

before_script:
 - composer self-update
 - composer install --prefer-dist --no-interaction

script:
 - vendor/bin/phpunit --fail-on-warning
