sudo: false
language: php
php:
 - '7.1'

env:
 - PHPU_VER=6 CUSTOM_ERROR_TRAP=0
 - PHPU_VER=6 CUSTOM_ERROR_TRAP=1
 - PHPU_VER=7 CUSTOM_ERROR_TRAP=0
 - PHPU_VER=7 CUSTOM_ERROR_TRAP=1

before_script:
 - composer self-update
 - composer require phpunit/phpunit:^$PHPU_VER --prefer-dist --no-interaction

script:
 - vendor/bin/phpunit --fail-on-warning
